version: '1'

services:
  db:
    image: 'postgres'
    container_name: 'employment-db'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=employment
    ports:
      - "5432:5432"
    volumes:
      - ~/employment-helper/employment/postgres:/var/lib/postgresql/data
  employment:
    image: 'employment'
    container_name: 'employment'
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/employment
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password